import './styles.css';
import {subjects,worksheets} from './data.js';
import {evaluate,status,loadProgress,saveProgress} from './progress.js';
import {downloadPdf} from './pdf.js';
const main=document.querySelector('main');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storage;try{storage=window.localStorage;}catch{storage=null;}
const progress=new Map(worksheets.map(w=>[w.id,loadProgress(storage,w)]));
let filter='all';let search='';
const labels={new:'Belum mulai',active:'Sedang dikerjakan',done:'Selesai'};
const state=w=>status(w,progress.get(w.id));
function privacy(){return '<p class="privacy">⌂ <strong>Progres hanya tersimpan di perangkat ini.</strong> Gunakan browser yang sama untuk melanjutkan. Menghapus data browser akan menghapus progres.</p>';}
function catalog(){const done=worksheets.filter(w=>state(w).state==='done').length;const active=worksheets.find(w=>state(w).state==='active');main.innerHTML=`
<section class="hero"><div><span class="eyebrow">PETUALANGAN BELAJAR · KELAS 1</span><h1>Hari ini, mau<br>belajar apa?</h1><p>Mulai dari rasa ingin tahu. Pilih lembar belajar,<br class="desktop"> coba sendiri, dan temukan hal baru!</p><a class="button primary" href="#worksheet/${active?.id??'math-1'}">${active?'Lanjutkan belajar':'Ayo mulai belajar'} <span aria-hidden="true">↗</span></a><span class="hero-note">5 soal singkat di setiap worksheet</span></div><div class="hero-art" aria-hidden="true"><span class="spark s1">✧</span><span class="spark s2">✦</span><div class="art-card card-back">A b c <span>♡</span></div><div class="art-card card-front"><span class="art-label">AKU BISA!</span><span class="art-sum">1 + 2 = <b>3</b></span><div class="art-dots">● ● ●</div><div class="art-lines"></div><span class="art-sticker">★</span></div><span class="pencil"></span><span class="spark s3">✧</span></div></section>
<section class="journey" aria-label="Progres belajar"><div><span class="journey-icon" aria-hidden="true">⚑</span><div><strong>Perjalanan belajarmu</strong><p>${done===0?'Setiap langkah kecil patut dirayakan.':`Hebat, ${done} lembar sudah kamu selesaikan!`}</p></div></div><div class="journey-progress"><span><strong>${done}</strong> / 20 selesai</span><progress value="${done}" max="20" aria-label="Worksheet selesai"></progress></div></section>
${privacy()}<section class="catalog"><div class="section-heading"><div><span class="eyebrow">PILIH, COBA, TEMUKAN</span><h2>Lembar belajarmu</h2></div><span class="count">20 worksheet · 4 mata pelajaran</span></div><div class="catalog-tools"><div class="filters" role="group" aria-label="Filter mata pelajaran"><button data-filter="all" aria-pressed="${filter==='all'}">Semua <span>20</span></button>${subjects.map(s=>`<button data-filter="${s.id}" aria-pressed="${filter===s.id}">${s.name} <span>5</span></button>`).join('')}</div><label class="search"><span class="sr-only">Cari worksheet</span><input type="search" placeholder="Cari topik belajar..." value="${escape(search)}" aria-label="Cari worksheet"></label></div><div class="worksheet-grid" id="cards"></div></section><aside class="parent-note"><span aria-hidden="true">✦</span><div><strong>Untuk orang tua & pendamping</strong><p>Dampingi anak membaca petunjuk, beri waktu untuk mencoba, dan rayakan usahanya. Ini draf pertama: materi belum ditinjau guru dan bukan klaim kesesuaian kurikulum resmi. PDF berisi soal kosong tanpa kunci jawaban.</p></div></aside>`;
renderCards();main.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;main.querySelectorAll('[data-filter]').forEach(btn=>btn.setAttribute('aria-pressed',String(btn===b)));renderCards();});main.querySelector('input[type=search]').oninput=e=>{search=e.target.value;renderCards();};}
function renderCards(){const shown=worksheets.filter(w=>(filter==='all'||w.subject===filter)&&`${w.title} ${w.topic} ${subjects.find(s=>s.id===w.subject).name}`.toLowerCase().includes(search.toLowerCase()));main.querySelector('#cards').innerHTML=shown.length?shown.map(w=>{const s=subjects.find(s=>s.id===w.subject),p=state(w);return `<article class="worksheet-card" style="--accent:${s.color}"><div class="card-top"><span class="subject-icon" aria-hidden="true">${s.icon}</span><span class="status ${p.state}">${labels[p.state]}</span></div><p class="subject-name">${s.name} <span>· ${String(w.order).padStart(2,'0')}</span></p><h3><a href="#worksheet/${w.id}">${w.title}</a></h3><p class="topic">${w.topic}</p><div class="card-meta"><span>5 soal · Kelas 1</span><span>${p.state==='done'?`${p.score}/5 benar`:'Draf v1'}</span></div><div class="card-actions"><a class="card-start" href="#worksheet/${w.id}">${p.state==='new'?'Mulai belajar':p.state==='done'?'Buka kembali':'Lanjutkan'} <span aria-hidden="true">→</span></a><button class="pdf-mini" data-pdf="${w.id}" aria-label="Download PDF ${w.title}">PDF ↓</button></div></article>`;}).join(''):'<p class="empty">Belum ada topik yang cocok. Coba kata lain, ya.</p>';main.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=()=>downloadPdf(worksheets.find(w=>w.id===b.dataset.pdf)));}
function worksheet(w){const s=subjects.find(s=>s.id===w.subject),p=progress.get(w.id);main.innerHTML=`<div class="worksheet-toolbar"><a href="#" class="back">← Kembali ke katalog</a><div><button class="button secondary" id="pdf">Download PDF ↓</button><button class="button secondary" id="print">Cetak</button></div></div><section class="worksheet-heading" style="--accent:${s.color}"><span class="subject-icon" aria-hidden="true">${s.icon}</span><span class="eyebrow">KELAS 1 · ${s.name.toUpperCase()} · LEMBAR ${w.order}</span><h1>${w.title}</h1><p>${w.topic}</p><span class="draft">Draf pertama · versi ${w.version} · perlu tinjauan guru</span></section>${privacy()}<div class="work-layout"><form id="answers" novalidate><p class="instructions">${w.instructions}</p>${w.questions.map((q,i)=>`<fieldset class="question" id="q-${i}"><legend><span class="question-number">${i+1}</span> ${escape(q.prompt)}</legend>${q.options?`<div class="options">${q.options.map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${escape(o)}" ${p.answers[i]===o?'checked':''}><span><b aria-hidden="true">${String.fromCharCode(65+j)}</b>${escape(o)}</span></label>`).join('')}</div>`:`<label class="answer-label" for="answer-${i}">Jawabanmu</label><input class="short-answer" id="answer-${i}" name="q${i}" type="text" ${q.type==='number'?'inputmode="numeric"':''} autocomplete="off" maxlength="100" value="${escape(p.answers[i]??'')}" placeholder="Tulis di sini...">`}<p class="feedback" id="feedback-${i}"></p></fieldset>`).join('')}<div class="answer-actions"><button class="button primary" type="submit">Periksa jawaban <span aria-hidden="true">✓</span></button><button class="button secondary" type="button" id="reset">Ulangi worksheet</button></div><p id="result" class="result" role="status" aria-live="polite"></p></form><aside class="work-aside"><span class="aside-star" aria-hidden="true">✦</span><h2>Pelan-pelan,<br>kamu bisa!</h2><p>Tidak apa-apa jika belum benar. Baca petunjuk dan coba lagi.</p><label for="answered">Soal terjawab</label><progress id="answered" max="5" value="0"></progress><p id="answered-text"></p><p id="save-status" role="status">${storage?'Jawaban disimpan otomatis di perangkat ini.':'Penyimpanan browser tidak tersedia. Jawaban hanya ada selama halaman ini terbuka.'}</p><hr><p>Ingin belajar di kertas? Unduh PDF atau cetak lembar soal kosong.</p></aside></div><section class="print-sheet"><h1>${w.title}</h1><p>Kelas 1 · ${s.name} · ${w.topic}</p><p>Draf pertama v${w.version} · Perlu tinjauan guru</p><p>Petunjuk: Lingkari pilihan atau tulis jawaban di ruang kosong.</p>${w.questions.map((q,i)=>`<div class="print-question"><h2>${i+1}. ${escape(q.prompt)}</h2>${q.options?`<ol type="A">${q.options.map(o=>`<li>${escape(o)}</li>`).join('')}</ol>`:''}<p>Jawaban: __________________________________________________</p></div>`).join('')}</section>`;
main.querySelector('#pdf').onclick=()=>downloadPdf(w);main.querySelector('#print').onclick=()=>window.print();const form=main.querySelector('form');
form.addEventListener('input',e=>{const match=e.target.name.match(/^q(\d+)$/);if(!match)return;p.answers[match[1]]=e.target.value;p.checked=false;persist(w,p);feedback(w,p);});
form.onsubmit=e=>{e.preventDefault();p.checked=true;persist(w,p);feedback(w,p);const missing=w.questions.findIndex((_,i)=>!String(p.answers[i]??'').trim());if(missing>=0)main.querySelector(`#q-${missing} input`).focus();};
main.querySelector('#reset').onclick=()=>{if(!confirm('Hapus jawaban worksheet ini dan mulai lagi?'))return;progress.set(w.id,{answers:{},checked:false});persist(w,progress.get(w.id));worksheet(w);main.querySelector('form input').focus();};feedback(w,p);}
function persist(w,p){const ok=saveProgress(storage,w,p);main.querySelector('#save-status').textContent=ok?'Jawaban tersimpan di perangkat ini.':'Penyimpanan browser tidak tersedia. Jawaban hanya ada selama halaman ini terbuka.';}
function feedback(w,p){const r=state(w);main.querySelector('#answered').value=r.count;main.querySelector('#answered-text').textContent=`${r.count} dari 5 soal terjawab`;
w.questions.forEach((q,i)=>{const el=main.querySelector(`#feedback-${i}`);const answered=String(p.answers[i]??'').trim();const correct=evaluate(q,p.answers[i]);el.textContent=p.checked?(answered?`${correct?'✓ Benar!':'Ayo coba lagi.'} ${q.explanation}`:'Isi jawaban ini dulu, ya.') : '';el.className=`feedback ${p.checked?(correct?'correct':'retry'):''}`;main.querySelectorAll(`#q-${i} input`).forEach(input=>{input.setAttribute('aria-describedby',`feedback-${i}`);input.setAttribute('aria-invalid',String(p.checked&&!correct));});});
main.querySelector('#result').textContent=p.checked?(r.state==='done'?`Worksheet selesai! ${r.score} dari 5 jawaban benar. ${r.score===5?'Hebat, kamu sudah mencoba semuanya!':'Kamu bisa mengubah jawaban dan memeriksanya lagi.'}`:`${r.count} dari 5 soal terisi. Lengkapi semua soal untuk menyelesaikan worksheet.`):'';}
function route(){const id=location.hash.match(/^#worksheet\/(.+)$/)?.[1];const w=worksheets.find(w=>w.id===id);if(w)worksheet(w);else catalog();window.scrollTo(0,0);main.focus({preventScroll:true});}
window.addEventListener('hashchange',route);route();
