export const subjects = [
 {id:'math',name:'Matematika',icon:'＋',color:'#e87535',description:'Bermain dengan angka'},
 {id:'indonesia',name:'Bahasa Indonesia',icon:'Aa',color:'#8661c5',description:'Membaca dan bercerita'},
 {id:'english',name:'Bahasa Inggris',icon:'Hi',color:'#3297ad',description:'Kenalan dengan kata baru'},
 {id:'ppkn',name:'PPKn',icon:'♡',color:'#ca647a',description:'Belajar hidup bersama'}
];
const choice=(prompt,options,answer,explanation)=>({type:'choice',prompt,options,answers:[answer],explanation});
const short=(prompt,answers,explanation,type='text')=>({type,prompt,answers:Array.isArray(answers)?answers:[answers],explanation});
const c=choice, n=(p,a,e)=>short(p,String(a),e,'number'), t=short;
const groups={
 math:[
 ['Angka di sekitarku','Mengenal bilangan 1–10',[n('Ada 2 apel dan 1 apel lagi. Ada berapa apel?',3,'Hitung: 2 + 1 = 3.'),c('Bilangan setelah 4 adalah ...',['3','5','6'],'5','Urutannya 3, 4, 5, 6.'),n('Tuliskan angka untuk kata tujuh.',7,'Tujuh ditulis 7.'),c('Bilangan yang paling kecil adalah ...',['2','5','8'],'2','2 lebih kecil daripada 5 dan 8.'),n('Ada 5 jari pada satu tangan. Berapa jumlah jarinya?',5,'Satu tangan memiliki 5 jari.')]],
 ['Ayo menjumlah!','Penjumlahan sampai 10',[n('2 + 2 = ...',4,'Dua ditambah dua menjadi empat.'),n('3 + 1 = ...',4,'Mulai dari 3, maju satu menjadi 4.'),c('Ada 4 pensil. Ditambah 2 pensil, menjadi ...',['5','6','7'],'6','4 + 2 = 6.'),n('5 + 3 = ...',8,'Setelah 5, hitung 6, 7, 8.'),n('6 + 4 = ...',10,'6 + 4 = 10.')]],
 ['Berkurang berapa?','Pengurangan sampai 10',[n('5 - 2 = ...',3,'Dari lima, ambil dua. Tersisa tiga.'),c('Ada 4 roti. 1 dimakan. Sisa roti adalah ...',['2','3','4'],'3','4 - 1 = 3.'),n('7 - 3 = ...',4,'Tujuh dikurangi tiga menjadi empat.'),n('10 - 5 = ...',5,'Sepuluh dikurangi lima menjadi lima.'),n('3 - 3 = ...',0,'Jika semuanya diambil, tersisa nol.')]],
 ['Detektif bentuk','Bentuk dan pola',[c('Bentuk yang memiliki 3 sisi adalah ...',['Segitiga','Lingkaran','Persegi'],'Segitiga','Segitiga memiliki tiga sisi.'),c('Bentuk yang tidak memiliki sudut adalah ...',['Persegi','Lingkaran','Segitiga'],'Lingkaran','Lingkaran berbentuk bulat tanpa sudut.'),c('Lanjutkan pola: merah, biru, merah, biru, ...',['Merah','Hijau','Kuning'],'Merah','Pola bergantian merah dan biru.'),c('Persegi memiliki berapa sisi?',['3','4','5'],'4','Persegi memiliki empat sisi sama panjang.'),c('Lanjutkan pola: 1, 2, 1, 2, ...',['1','3','4'],'1','Pola mengulang 1 lalu 2.')]],
 ['Bandingkan dan urutkan','Perbandingan bilangan',[c('Mana yang lebih banyak?',['3 kelereng','7 kelereng'],'7 kelereng','7 lebih besar daripada 3.'),n('Lengkapi urutan: 6, 7, ..., 9.',8,'Setelah 7 adalah 8.'),c('Mana yang lebih sedikit?',['2 buku','5 buku'],'2 buku','2 lebih kecil daripada 5.'),c('Bilangan antara 2 dan 4 adalah ...',['1','3','5'],'3','Urutannya 2, 3, 4.'),c('Urutan dari kecil ke besar adalah ...',['1, 3, 5','5, 3, 1','3, 1, 5'],'1, 3, 5','1 paling kecil, lalu 3, lalu 5.')]]
 ],
 indonesia:[
 ['Kenalan dengan huruf','Huruf dan bunyi',[c('Huruf pertama pada kata buku adalah ...',['b','d','k'],'b','Kata buku dimulai dengan b.'),t('Tuliskan huruf pertama pada kata mata.','m','Kata mata dimulai dengan m.'),c('Manakah huruf vokal?',['a','b','d'],'a','Huruf vokal adalah a, i, u, e, o.'),c('Kata yang dimulai dengan s adalah ...',['sapi','buku','meja'],'sapi','Sapi dimulai dengan huruf s.'),t('Tuliskan huruf terakhir pada kata topi.','i','Kata topi diakhiri dengan i.')]],
 ['Merangkai suku kata','Membaca kata sederhana',[c('ba + ju menjadi ...',['baju','batu','buku'],'baju','Gabungkan ba dan ju menjadi baju.'),t('Gabungkan bo + la menjadi satu kata.','bola','Bo dan la membentuk bola.'),c('Suku kata pada kata meja adalah ...',['me-ja','ma-je','mi-ja'],'me-ja','Meja dibaca me-ja.'),t('Gabungkan sa + pi menjadi satu kata.','sapi','Sa dan pi membentuk sapi.'),c('ku + da menjadi ...',['kuda','kado','kaki'],'kuda','Ku dan da membentuk kuda.')]],
 ['Kata di rumah','Kosakata benda',[c('Benda untuk duduk adalah ...',['kursi','sendok','bantal'],'kursi','Kita duduk di kursi.'),c('Kita membaca ...',['buku','sepatu','piring'],'buku','Buku berisi tulisan untuk dibaca.'),t('Lengkapi: Aku minum ... putih.','air','Kita minum air putih.'),c('Benda untuk menulis adalah ...',['pensil','gelas','bola'],'pensil','Pensil digunakan untuk menulis.'),c('Kita memakai ... di kaki.',['topi','sepatu','baju'],'sepatu','Sepatu dipakai di kaki.')]],
 ['Cerita tentang Siti','Memahami bacaan pendek',[c('Siti menyiram bunga. Siapa yang menyiram bunga?',['Siti','Budi','Ibu'],'Siti','Dalam kalimat, Siti menyiram bunga.'),c('Siti menyiram bunga. Apa yang disiram Siti?',['Bunga','Buku','Meja'],'Bunga','Yang disiram adalah bunga.'),c('Budi membawa buku ke sekolah. Apa yang dibawa Budi?',['Bola','Buku','Roti'],'Buku','Budi membawa buku.'),c('Budi membawa buku ke sekolah. Ke mana Budi pergi?',['Sekolah','Pasar','Pantai'],'Sekolah','Budi pergi ke sekolah.'),c('Kucing tidur di kursi. Di mana kucing tidur?',['Di kursi','Di pohon','Di jalan'],'Di kursi','Bacaan menyebut kucing tidur di kursi.')]],
 ['Kalimat ramah','Kalimat dan ungkapan',[c('Saat menerima bantuan, kita berkata ...',['Terima kasih','Selamat tidur','Sampai jumpa'],'Terima kasih','Terima kasih menunjukkan rasa syukur atas bantuan.'),c('Saat berbuat salah, kita berkata ...',['Maaf','Halo','Selamat pagi'],'Maaf','Kita meminta maaf ketika berbuat salah.'),c('Kalimat yang benar adalah ...',['Aku makan nasi.','Nasi aku makan pergi.','Makan aku pergi nasi.'],'Aku makan nasi.','Aku makan nasi adalah kalimat yang jelas.'),c('Saat meminta bantuan, kata yang ramah adalah ...',['Tolong','Cepat!','Pergi!'],'Tolong','Tolong adalah kata yang sopan untuk meminta bantuan.'),c('Tanda di akhir kalimat Aku membaca buku adalah ...',['Titik (.)','Koma (,)','Tanda tanya (?)'],'Titik (.)','Kalimat pernyataan diakhiri dengan titik.')]]
 ],
 english:[
 ['Hello, teman!','Salam sederhana',[c('Hello berarti ...',['Halo','Terima kasih','Maaf'],'Halo','Hello digunakan untuk menyapa.'),c('Selamat pagi dalam bahasa Inggris adalah ...',['Good morning','Good night','Goodbye'],'Good morning','Good morning adalah salam pagi.'),c('Goodbye berarti ...',['Sampai jumpa','Selamat pagi','Tolong'],'Sampai jumpa','Goodbye diucapkan saat berpisah.'),t('Lengkapi salam: Good ... (selamat pagi).','morning','Good morning berarti selamat pagi.'),c('Thank you berarti ...',['Terima kasih','Halo','Selamat malam'],'Terima kasih','Thank you diucapkan saat berterima kasih.')]],
 ['Warna favorit','Colors',[c('Red berarti warna ...',['Merah','Biru','Hijau'],'Merah','Red adalah merah.'),t('Bahasa Inggris untuk biru adalah ...','blue','Blue adalah biru.'),c('Yellow berarti ...',['Kuning','Hitam','Putih'],'Kuning','Yellow adalah kuning.'),c('Bahasa Inggris untuk hijau adalah ...',['Green','Red','Blue'],'Green','Green adalah hijau.'),t('Bahasa Inggris untuk putih adalah ...','white','White adalah putih.')]],
 ['One, two, three!','Numbers 1–5',[c('One berarti ...',['Satu','Dua','Tiga'],'Satu','One adalah satu.'),t('Bahasa Inggris untuk dua adalah ...','two','Two adalah dua.'),c('Three berarti ...',['Dua','Tiga','Lima'],'Tiga','Three adalah tiga.'),t('Lengkapi: one, two, three, ... , five.','four','Four berarti empat.'),c('Five berarti ...',['Tiga','Empat','Lima'],'Lima','Five adalah lima.')]],
 ['Teman hewan','Animals',[c('Cat berarti ...',['Kucing','Anjing','Burung'],'Kucing','Cat adalah kucing.'),t('Bahasa Inggris untuk anjing adalah ...','dog','Dog adalah anjing.'),c('Bird berarti ...',['Burung','Ikan','Sapi'],'Burung','Bird adalah burung.'),c('Bahasa Inggris untuk ikan adalah ...',['Fish','Cat','Cow'],'Fish','Fish adalah ikan.'),t('Cow berarti hewan apa?','sapi','Cow adalah sapi.')]],
 ['Di dalam tas','School objects',[c('Book berarti ...',['Buku','Tas','Penggaris'],'Buku','Book adalah buku.'),t('Bahasa Inggris untuk pensil adalah ...','pencil','Pencil adalah pensil.'),c('Bag berarti ...',['Tas','Meja','Buku'],'Tas','Bag adalah tas.'),c('Bahasa Inggris untuk penggaris adalah ...',['Ruler','Book','Bag'],'Ruler','Ruler adalah penggaris.'),t('Pen berarti alat tulis apa?',['pena','pulpen','bolpoin'],'Pen adalah pena atau pulpen.')]]
 ],
 ppkn:[
 ['Aku dan teman-temanku','Menghargai perbedaan',[c('Teman memiliki hobi berbeda. Kita sebaiknya ...',['Menghargai hobinya','Mengejeknya','Menjauhinya'],'Menghargai hobinya','Setiap teman boleh memiliki hobi berbeda.'),c('Ada teman baru di kelas. Kita ...',['Menyapanya','Mengabaikannya','Menertawakannya'],'Menyapanya','Menyapa membuat teman merasa diterima.'),c('Teman berbicara. Kita sebaiknya ...',['Mendengarkan','Memotong pembicaraan','Berteriak'],'Mendengarkan','Mendengarkan adalah cara menghargai teman.'),c('Teman memiliki agama berbeda. Kita ...',['Menghormatinya','Mengejeknya','Memaksanya ikut kita'],'Menghormatinya','Kita menghormati agama setiap orang.'),c('Saat bermain bersama, kita ...',['Memberi semua teman kesempatan','Memilih diri sendiri terus','Melarang teman ikut'],'Memberi semua teman kesempatan','Semua teman berhak ikut bermain.')]],
 ['Aturan membuat nyaman','Aturan di sekolah',[c('Sebelum berbicara di kelas, kita ...',['Mengangkat tangan','Berteriak','Memukul meja'],'Mengangkat tangan','Mengangkat tangan membantu kita bergiliran.'),c('Saat antre, kita ...',['Menunggu giliran','Menyerobot','Mendorong teman'],'Menunggu giliran','Antre berarti menunggu giliran.'),c('Sampah sebaiknya dibuang ...',['Di tempat sampah','Di lantai','Di meja'],'Di tempat sampah','Tempat sampah membantu menjaga kebersihan.'),c('Saat pelajaran dimulai, kita ...',['Menyiapkan alat belajar','Berlari di kelas','Mengganggu teman'],'Menyiapkan alat belajar','Alat belajar membantu kita siap mengikuti pelajaran.'),c('Setelah meminjam buku kelas, kita ...',['Mengembalikannya','Menyembunyikannya','Merobeknya'],'Mengembalikannya','Barang pinjaman perlu dikembalikan.')]],
 ['Saling membantu','Kerja sama',[c('Teman kesulitan merapikan buku. Kita ...',['Membantu jika ia mau','Menertawakan','Mengambil bukunya'],'Membantu jika ia mau','Tawarkan bantuan dengan ramah.'),c('Saat membersihkan kelas bersama, kita ...',['Berbagi tugas','Membiarkan satu teman bekerja','Mengotori lantai'],'Berbagi tugas','Berbagi tugas membuat pekerjaan lebih ringan.'),c('Pensil teman jatuh. Kita ...',['Membantu mengambilnya','Menyembunyikannya','Membuangnya'],'Membantu mengambilnya','Bantuan kecil juga berarti bagi teman.'),c('Dalam permainan kelompok, kita ...',['Bekerja sama','Bertengkar','Meninggalkan kelompok'],'Bekerja sama','Kerja sama membantu kelompok bermain dengan baik.'),c('Setelah dibantu teman, kita ...',['Berterima kasih','Mengejeknya','Diam dan pergi'],'Berterima kasih','Ucapan terima kasih menghargai bantuan teman.')]],
 ['Tanggung jawab kecilku','Tanggung jawab di rumah',[c('Setelah bermain, mainan sebaiknya ...',['Dirapikan','Dibiarkan berserakan','Dilempar'],'Dirapikan','Merapikan mainan adalah tanggung jawab kita.'),c('Sebelum makan, kita ...',['Mencuci tangan','Bermain lumpur','Memegang sampah'],'Mencuci tangan','Tangan bersih membantu menjaga kesehatan.'),c('Jika tidak sengaja menumpahkan air, kita ...',['Memberi tahu orang dewasa dan membantu membersihkan','Menyalahkan teman','Membiarkannya'],'Memberi tahu orang dewasa dan membantu membersihkan','Minta bantuan agar lantai tidak licin.'),c('Saat selesai memakai buku, kita ...',['Menyimpannya dengan rapi','Merobeknya','Membuangnya'],'Menyimpannya dengan rapi','Merawat buku membuatnya dapat digunakan lagi.'),c('Jika berjanji merapikan pensil, kita ...',['Melakukannya','Melupakannya sengaja','Menyuruh teman terus'],'Melakukannya','Menepati janji adalah bentuk tanggung jawab.')]],
 ['Mengenal Indonesia','Simbol negara',[c('Warna bendera Indonesia adalah ...',['Merah dan putih','Biru dan putih','Hijau dan kuning'],'Merah dan putih','Bendera Indonesia berwarna merah di atas dan putih di bawah.'),c('Lambang negara Indonesia adalah ...',['Garuda Pancasila','Kucing','Pohon kelapa'],'Garuda Pancasila','Garuda Pancasila adalah lambang negara Indonesia.'),c('Pancasila memiliki ... sila.',['3','4','5'],'5','Pancasila memiliki lima sila.'),c('Saat upacara bendera, kita bersikap ...',['Tertib','Bercanda keras','Berlari-lari'],'Tertib','Sikap tertib menunjukkan rasa hormat.'),c('Lagu kebangsaan Indonesia adalah ...',['Indonesia Raya','Balonku','Pelangi'],'Indonesia Raya','Indonesia Raya adalah lagu kebangsaan Indonesia.')]]
 ]
};
export const worksheets=subjects.flatMap(s=>groups[s.id].map(([title,topic,questions],i)=>({id:`${s.id}-${i+1}`,subject:s.id,grade:1,order:i+1,version:'1',publicationStatus:'draft',title,topic,instructions:'Baca soal perlahan. Pilih atau tulis jawabanmu, lalu tekan Periksa jawaban.',questions})));
